name: Build branch
run-name: Build branch
on:
  push:
    branches: [ "!main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      
      - uses: actions/checkout@v2
      
      - name: lake update
        run: lake update
        
      - name: get cache
        run: lake exe cache get
      
      - name: build game
        run: env LEAN_ABORT_ON_PANIC=1 lake build
